# .github/workflows/main.yml
name: Atualizar e Publicar Dashboard

on:
  push:
    branches:
      - main # Executa sempre que houver uma alteração no código principal
  workflow_dispatch: # Permite executar manualmente
  schedule:
    - cron: '0 8 * * *' # Executa todos os dias às 08:00 (UTC)

# Permissões necessárias para a nova Action de publicação
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: 3. Instalar as Bibliotecas
        run: pip install -r requirements.txt

      - name: 4. Executar scripts para gerar o dashboard
        run: |
          python main.py
          python gerar_dashboard.py
        env:
          DMG_USER_TOKEN: ${{ secrets.DMG_USER_TOKEN }}

      - name: 5. Fazer o Upload do Artefacto para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    # O deploy só acontece depois de o 'build' ser bem-sucedido
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publicar o Artefacto no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4